# Generated by Django 5.1.15 on 2026-07-13 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('target_ip', models.GenericIPAddressField()),
                ('target_url', models.URLField(blank=True, default='', max_length=2000)),
                ('url_scheme', models.CharField(blank=True, default='', max_length=8)),
                ('url_hostname', models.CharField(blank=True, default='', max_length=255)),
                ('url_port', models.PositiveIntegerField(blank=True, null=True)),
                ('url_base_path', models.CharField(blank=True, default='/', max_length=1000)),
                ('profile', models.CharField(choices=[('SAFE', '安全 (Safe)'), ('STANDARD', '標準 (Standard)')], default='SAFE', max_length=16)),
                ('requested_tools', models.JSONField(default=list)),
                ('tool_config', models.JSONField(default=dict)),
                ('rate_limit', models.PositiveIntegerField(default=50)),
                ('max_duration', models.PositiveIntegerField(default=3600)),
                ('status', models.CharField(choices=[('CREATED', '已建立'), ('QUEUED', '排隊中'), ('RUNNING', '執行中'), ('CANCELLING', '取消中'), ('CANCELLED', '已取消'), ('COMPLETED', '已完成'), ('PARTIAL', '部分完成'), ('FAILED', '失敗'), ('TIMED_OUT', '逾時')], default='CREATED', max_length=16)),
                ('authorized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('QUEUED', '排隊中'), ('RUNNING', '執行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗'), ('SKIPPED', '略過'), ('CANCELLED', '已取消'), ('TIMED_OUT', '逾時')], default='PENDING', max_length=16)),
                ('progress', models.PositiveIntegerField(blank=True, null=True)),
                ('command_mode', models.CharField(choices=[('DEFAULT', '預設'), ('EXPERT', '進階自訂')], default='DEFAULT', max_length=8)),
                ('expert_command_text', models.TextField(blank=True, default='')),
                ('argv', models.JSONField(default=list)),
                ('display_command', models.CharField(blank=True, default='', max_length=4000)),
                ('container_id', models.CharField(blank=True, default='', max_length=128)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('tool_version', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recon.scantask')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('content_length', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=256)),
                ('redirect_location', models.CharField(blank=True, default='', max_length=2000)),
                ('in_scope', models.BooleanField(default=True)),
                ('source_tools', models.JSONField(default=list)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='recon.scantask')),
            ],
            options={
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recon.scanstep')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recon.scantask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('artifact_type', models.CharField(default='file', max_length=64)),
                ('rel_path', models.CharField(max_length=1000)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='recon.scanstep')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='recon.scantask')),
            ],
            options={
                'ordering': ['rel_path'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('transport', models.CharField(default='tcp', max_length=8)),
                ('service_name', models.CharField(blank=True, default='', max_length=128)),
                ('product', models.CharField(blank=True, default='', max_length=256)),
                ('version', models.CharField(blank=True, default='', max_length=128)),
                ('extra_info', models.CharField(blank=True, default='', max_length=512)),
                ('source_tool', models.CharField(blank=True, default='', max_length=64)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='recon.scantask')),
            ],
            options={
                'ordering': ['port'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', '資訊'), ('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '嚴重')], default='info', max_length=16)),
                ('confidence', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('remediation', models.TextField(blank=True, default='')),
                ('source_tool', models.CharField(blank=True, default='', max_length=64)),
                ('dedup_key', models.CharField(db_index=True, max_length=64)),
                ('related_endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.endpoint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='recon.scantask')),
                ('related_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recon.service')),
            ],
            options={
                'ordering': ['severity', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['status'], name='recon_scant_status_c28965_idx'),
        ),
        migrations.AddIndex(
            model_name='scantask',
            index=models.Index(fields=['created_at'], name='recon_scant_created_8906e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scanstep',
            unique_together={('task', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='endpoint',
            unique_together={('task', 'url', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='artifact',
            unique_together={('task', 'rel_path')},
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('task', 'ip', 'port', 'transport')},
        ),
        migrations.AlterUniqueTogether(
            name='finding',
            unique_together={('task', 'dedup_key')},
        ),
    ]
